name: PR comments
on:
  pull_request:
    branches: [ "main" ]
jobs:
  prcomment:
    name: Read PR Comments
    runs-on: ubuntu-latest
    steps:
    - run: gem install octokit -v 4.15.0 --user-install
    - uses: actions/checkout@v3
    - run: ruby -r ./.github/workflows/octokit.rb > rubyout.log
    - run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - run: echo $NOW # Gives "2022-12-11T01:42:20"
    - run: echo "do something"
    - run: chomd +x ./.github/workflows/findit.sh
    - run: ./.github/workflows/findit.sh
